@startuml

actor User
participant RequestService
participant EmailService
queue Kafka

User -> RequestService: Request
RequestService -> Kafka: Request Message
Kafka -> RequestService: Message Produced

loop
Kafka -> EmailService: Request Message
EmailService -> User: Confirmation Email
EmailService -> Kafka: Message Consumed
end

@enduml