@startuml

actor User
participant RequestService
participant EmailService
queue Redis

User -> RequestService: Request
RequestService -> Redis: Request Message
Redis -> RequestService: Message Produced

loop
Redis -> EmailService: Request Message
EmailService -> User: Confirmation Email
EmailService -> Redis: Message Consumed
end

@enduml